### PR TITLE
Serkan

### PR DESCRIPTION
**Pull request by Serkan-C**
in this request i change only my files which are the followings:
src/test/java/com/tryCloud/pages/TalkModulePage.java
src/test/java/com/tryCloud/step_definitions/TalkModuleStepDefinitions.java
src/test/resources/features/TalkModule.feature
I dont think that it will affect the coding .
it is already working in my computer.

### CODE REVIEW

**Comment by elifdmrr** [comment]
there is conflict with this branch

**Review by furkankavrik — APPROVED** [review]
Locators are added and  Serkan added his codes related to his US

**Review by furkankavrik — COMMENTED** [review]
ok

**Review by mohmojahed — APPROVED** [review]
Done

**Pull request merged**
